language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
script: nosetests
notifications:
  email:
    recipients:
      - mauro.stettler@gmail.com
    on_success: change
    on_failure: change
